[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.extensions.gd",
  "php82Packages.extensions.curl",
  "php82Packages.extensions.mbstring",
  "php82Packages.extensions.pdo",
  "php82Packages.extensions.pdo_mysql"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci"
]

[build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

